name: Test Action
on:
  push:
    branches:
      - main  # or any branch you want to trigger the action
jobs:
  test:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: 23f1001420@ds.study.iitm.ac.in
        run: echo "Hello, world!"
